#!/usr/bin/perl

name: BitRoad
short: BR
uri: qr{bitroad\.net/}
status: OK 2009-10-22

start:
	GET( $-{_uri} );

	ERROR( "file not found" )
		if /The requested file is not found/;

	m#<div class="content_text"><h1>(.*?)\s*\[ ($STDSIZE) \]</h1>#;
	INFO( name => $1, asize => $2 );

	RESTART( -(60 + int rand 300), "free limit reached" )
		if /Downloading is in process from your IP-Address/;

	$-{form} = $self->form( match => { action => qr{^/download3\.php$} } );
	CLICK_DOWNLOAD( $-{form}->post() );

# vim:ts=4:sw=4
