#!/usr/bin/perl

name: FlyfileUs
short: FU
uri: qr{flyfile\.us/}
status: OK 2009-10-22

start:
	GET( $-{_uri} );

	ERROR( "file not found" ) if /(No such file|No such user)/;
	m{<h2>Download File (.*?)</h2>};
	$-{name} = $1;

	! my $form = $self->form( match => { body => qr/"Free Download"/ } );
	$form->set( method_free => "Free Download" );
	CLICK( $form->post() );

	ERROR( "file removed" )
		if m{<font class="err">File was deleted by administrator</font>};

	m{<small>\((\d+) bytes\)</small>};
	INFO( name => $-{name}, size => $1 );

	RESTART( 600, "download-limit reached" )
		if /You have reached the download-limit/;

	! my $form = $self->form( name => "F1" );
	CLICK_DOWNLOAD( $form->post() );

	RESTART( 120, "temporarily unavailable" )
		if /temporarily unavailable/;

# vim:ts=4:sw=4
