#!/usr/bin/perl

name: OdSiebie
short: OS
uri: qr{odsiebie\.com/pokaz/}
cookie: os
slots: 8
status: OK 2009-08-28

start:
	GET( $-{_uri} );

	ERROR( "some problem, file not found ?" )
		if $-{_referer} =~ m{/(upload|error)\.html};

	m{<dl\s+class="file-info">.*?<dd.*?>
		(?:\s*<!--.*?-->\s*<!--.*?-->\s*)?
		(.*?)
		</dd>.*?<dd>\s*($STDSIZE)</dd>}sx;
	INFO( name => $1, asize => $2 );

	! m{href="(/pobierz/\d+---.*?(\.html)?)"};
	GET( $1 );

	! m{href="(/download/\d+---.*?.html)"};
	DOWNLOAD( $1 );

# vim:ts=4:sw=4
