#!/usr/bin/perl

name: StorageTo
short: ST
uri: qr{storage\.to/get/[a-zA-Z0-9]{8}([\?/].*?)?$}
status: OK 2009-10-23

start:
	GET( $-{_uri} );

	ERROR( "file not found" ) if /File not found\./;
	! m{<span class="orange">.*?:</span> (.*?) <span class="light">\(($STDSIZE)\)</span>};
	INFO( name => $1, asize => $2 );

	! /onclick='javascript:startcountdown\("(.*?)",\s*"(?:.*?)",\s*"(.*?)"\);'/;
	CLICK( "/getlink/$2/" );

	! s/^.*?{\s+//;
	! s/\s+}.*?$//;

	ERROR( "download failed" ) if /'state'\s*:\s*'failed'/;

	! /'countdown'\s*:\s*(\d+)/;
	my $wait = $1;
	RESTART( $wait, "free limit reached" )
		unless /'state'\s*:\s*'ok'/;

	! /'link'\s*:\s*'(.*?)'/ and $1;
	$-{file_uri} = $1;

	WAIT( $wait, "starting download" );

	delete $-{_referer}; # started from ajax, there must be no referer
	CLICK_DOWNLOAD( $-{file_uri} );

# vim:ts=4:sw=4
