#!/usr/bin/perl

name: zSHARE
short: zS
uri: qr{zshare\.net}
#cookie: zs
slots: max
status: OK 2009-10-22

start:
	GET( $-{_uri} );

	ERROR( "file not found" ) if $-{_referer} =~ /file-404.html$/;

	! m{>File Name:\s*<font.*?>(.*?)</font></td>}s;
	my $name = $1;
	! m{>File Size:\s*<font.*?>($STDSIZE)</font></td>}s;
	INFO( name => $name, asize => $1 );

	! my $form = $self->form( name => "form1" );
	$form->set( "imageField.x" => 10 + int rand 180 );
	$form->set( "imageField.y" => 10 + int rand 37 );
	$form->set( "imageField" => "" );

	CLICK( $form->post() );

	! m{var link_enc=new Array\('(.*?)'\);};
	( $-{uri} = $1 ) =~ s/','//g;

	WAIT( 50, "starting download" );

	CLICK_DOWNLOAD( $-{uri} );

# vim:ts=4:sw=4
