#!/usr/bin/perl

name: CryptedBiz
short: crypted.biz
uri: qr{crypted\.biz/}
slots: max
status: OK 2009-08-27

pre:
	use MIME::Base64;

start:
	GET( $-{_uri} );

	my @list;
	push @list, $1
		while s/className='inner_link\d+';window\.open\('(.*?)'\)">//;

	ERROR("no links") unless @list;

	$-{list} = \@list;
	$-{outlist} = [];

stage_get_link:
	GET( shift @{$-{list}}, keep_referer => 1 );
	m{var versch = '(.*?)';};
	$_ = decode_base64( $1 );
	m{ src="(.*?)">};
	push @{$-{outlist}}, $1;

	GOTO stage_get_link if @{$-{list}};

	LINK( @{$-{outlist}} );

# vim:ts=4:sw=4
