#!/usr/bin/perl

name: LinkHider
short: linkhider.com
uri: qr{linkhider\.com/}
status: OK 2009-08-25

start:
	GET( $-{_uri} );
	
	! m{<META HTTP-EQUIV="refresh" CONTENT="\d+;url='(.*?)'">};

	LINK( $1 );

# vim:ts=4:sw=4
