#!/usr/bin/perl

name: RaidRush
short: L:RaidRush
uri: qr{save\.raidrush\.ws/}
slots: max
status: OK 2009-10-04

start:
	GET( $-{_uri} );

	my @list;
	push @list, "/404.php.php?id=$1&key=$2"
		while s/onclick="get\('(.*?)','FREE','(.*?)'\)//;

	ERROR("no links") unless @list;

	$-{list} = \@list;
	$-{outlist} = [];

stage_get_link:
	GET( shift @{$-{list}} );
	push @{$-{outlist}}, "http://" . $_;

	GOTO stage_get_link if @{$-{list}};

	LINK( @{$-{outlist}} );

# vim:ts=4:sw=4
