#!/usr/bin/perl

name: RaidRush
short: save.raidrush.ws
uri: qr{save\.raidrush\.ws/}
status: OK 2009-08-25

start:
	GET( $-{_uri} );
	$-{referer} = $-{_referer};

	my @list;
	push @list, "/404.php.php?id=$1&key=$2"
		while s/onclick="get\('(.*?)','FREE','(.*?)'\)//;
	ERROR("no links") unless @list;
	$-{list} = \@list;
	$-{outlist} = [];

	GET( shift @{$-{list}} );
stage_next_uri:
	push @{$-{outlist}}, "http://" . $_;

	if ( @{$-{list}} ) {
		$-{_referer} = $-{referer};
		GET_NEXT( stage_next_uri, shift @{$-{list}} );
	}

	LINK( @{$-{outlist}} );

# vim:ts=4:sw=4
