#!/usr/bin/perl

name: ShareBee
short: L:ShareBee
uri: qr{sharebee\.com/}
slots: max
status: OK 2009-10-24

start:
	GET( $-{_uri} );

	ERROR( "file not found" ) if m{<title>404 - Page not found};
	! m{<table class="links".*?>(.*?)</table>}s;
	my $tbody = $1;
	my @links = ($tbody =~ /a href="(.*?)"/g);

	LINK( @links );

# vim:ts=4:sw=4
