#!/usr/bin/perl

name: Google
short: V:Google
uri: qr{video\.google\.com/videoplay\?}
slots: max
status: OK 2009-10-04

start:
	GET( $-{_uri} );

	! m{<title>(.*?)</title>};
	my $name = de_ml( $1 );
	$name =~ s{/}{_}g;

	my @file_uri;
	if ( /<a href=(http.*?ck1)>/ ) {
		@file_uri = ( $1 );
		INFO( ainame => $name, quality => "mp4" );
	} else {
		! m{videoUrl\\x3d(.*?)\\x26};
		@file_uri = (uri_unescape( $1 ),
			fname => "$name.flv" );
		INFO( name => "$name.flv", quality => "flv" );
	}

	DOWNLOAD( @file_uri );

# vim:ts=4:sw=4
