#!/usr/bin/perl

name: SpankWire
short: V:SpankWire
uri: qr{spankwire\.com/}
slots: 8
status: OK 2009-10-05

start:
	GET( $-{_uri} );

	! m{<title>(.*?)</title>};
	$-{fname} = de_ml( $1 );
	$-{fname} =~ s{/}{_}g;
	$-{fname} .= ".flv";

	INFO( name => $-{fname}, quality => "flv" );

	! m{videoPath:"(/Player/VideoXML.*?)"};
	my $uri = uri_unescape( $1 );
	GET( $uri );

	! m{<url type="string">(.*?)</url>};
	my $file_uri = de_ml( $1 );
	DOWNLOAD( $file_uri, fname => $-{fname} );

# vim:ts=4:sw=4
