#!/usr/bin/perl

name: Vimeo
short: V:Vimeo
uri: qr{vimeo\.com/}
slots: 8
status: OK 2009-10-05

start:
	GET( $-{_uri} );

	ERROR( "file not found" ) if /Page not found/;

	! m{clip_id=(\d+)};
	$-{id} = $1;

	GET( "http://vimeo.com/moogaloop/load/clip:$-{id}" );

	! m{<width>(\d+)</width>};
	my $w = $1;
	! m{<height>(\d+)</height>};
	my $h = $1;
	! m{<caption>(.*?)</caption>};
	my $name = $1;
	$name .= ".flv";
	INFO( name => $name, quality => "${w}x${h}" );

	! m{<request_signature>(.*?)</request_signature>};
	my $rs = $1;
	! m{<request_signature_expires>(\d+)</request_signature_expires>};
	my $rse = $1;

	my $file_uri = "http://vimeo.com/moogaloop/play/clip:$-{id}/$rs/$rse/?q=hd";
	DOWNLOAD( $file_uri, fname => $name );

# vim:ts=4:sw=4
