#!/usr/bin/perl

name: YouTube
short: V:YouTube
uri: qr{youtube\.com/watch\?v=.*}
slots: 8
status: OK 2009-10-03

start:
	! $-{_uri} =~ m{[\?&]v=([-_a-zA-Z0-9]+)(?:&.*)?$};
	$-{v} = $1;

	GET( "http://www.youtube.com/watch?v=$-{v}" );

	! m{<meta name="title" content="(.*?)">};
	my $name = de_ml( $1 );
	$name =~ s{/}{_}g;

	! /"fmt_map"\s*:\s*"(.*?)"/;
	my %fmts = map { m{(\d+)/}; $1 => $_ } split ",", uri_unescape( $1 );

	my $fmt = "18";
	$fmt = "35" if $fmts{35};
	$fmt = "22" if $fmts{22};

	my $ext = "mp4";
	$ext = "flv" if $fmt eq "35";

	! /"t"\s*:\s*"(.*?)"/;
	my $t = $1;

	my $fname = $name . "." . $ext;
	INFO( name => $fname, quality => "fmt$fmt" );

	DOWNLOAD( "http://youtube.com/get_video?video_id=$-{v}&t=$t&fmt=$fmt",
		fname => $fname );

# vim:ts=4:sw=4
