#!/usr/bin/perl

use strict;
use warnings;

open F_LIST, ">", "test.list";
open F_ORIG, ">", "test.list.orig";

while ( my $file = shift @ARGV ) {
	open F_IN, "<", $file or die;

	my $src = "# source: $file\n";
	print $src;
	print F_LIST $src;
	print F_ORIG $src;

	while ( <F_IN> ) {
		print F_ORIG $_;
		if ( /#\s*src:\s*(.+)/ ) {
			print F_LIST $_;
			print F_LIST $1 . "\n";
		} elsif ( /^# invalid uri:/ ) {
			# nothing here
		} elsif ( /^(#.*|)$/ ) {
			print F_LIST $_;
		}
	}

	close F_IN;

	print F_LIST "\n";
	print F_ORIG "\n";
}

close F_LIST and print "wrote test.list\n";
close F_ORIG and print "wrote test.list.orig\n";
